### ISSUE TITLE
Images not seen 

### ISSUE THREAD

**Issue by SridharShrinidhi** [SridharShrinidhi/interactive-polaroids#1]
@hellachella Images not seen for comparison

**Comment by hellachella** [comment]
```
.polaroid:first-child {
  left: 30%;
  top: 20%;
  z-index: 1;
  transform: rotate(-20deg);
}

.polaroid:nth-child(2) {
  left: 40%;
  top: 30%;
  transform: rotate(10deg);
  z-index: 3;
}

.polaroid:last-child {
  left: 50%;
  top: 20%;
  z-index: 2;
  transform: rotate(30deg);
}
```
I think the culprit might be the ` top: 20%;`, ` top: 30%;`, ` top: 20%;`

Instead try using a more concrete value such as pixels or ems instead of percentages. Basically, I think it is pushing everything too far below.

**Comment by SridharShrinidhi** [comment]
Yes, that was the problem, I changed it to pixels and it magically appeared! The difference is now less than 10%. 
Thanks so much!

**Comment by hellachella** [comment]
YAY!
